### ISSUE TITLE
Making http post request to NVIDIA-XAVIER Inference server generates 500 error

### ISSUE THREAD

**Issue by Kapil-23** [roboflow-ai/inference-server#8]
Hello,

I am making an http post request by using the below code to Inference server.
Taken Reference from : [Roboflow-hosted-api](https://docs.roboflow.com/inference/hosted-api#uploading-a-local-image-using-multipart-form-recommended)
```
import io
import cv2
import requests
from PIL import Image
from requests_toolbelt.multipart.encoder import MultipartEncoder

# Load Image with PIL
img = cv2.imread("sample.jpg")
image = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
pilImage = Image.fromarray(image)

# Convert to JPEG Buffer
buffered = io.BytesIO()
pilImage.save(buffered, quality=100, format="JPEG")

# Build multipart form and post request
m = MultipartEncoder(fields={'file': ("imageToUpload", buffered.getvalue(), "image/jpeg")})

response = requests.post("http://xx.xx.xx.xxx:xxxx/sample-pro/1?api_key=xxxx", data=m, headers={'Content-Type': m.content_type})

print(response)
print(response.json())
```
**Response : 500**

INFERENCE SERVER LOG:
```
inference-server is ready to receive traffic.
TypeError: req.body.replace is not a function
    at transformImageBody (/inference-server/server/index.js:308:26)
    at Layer.handle [as handle_request] (/inference-server/server/node_modules/express/lib/router/layer.js:95:5)
    at next (/inference-server/server/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/inference-server/server/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/inference-server/server/node_modules/express/lib/router/layer.js:95:5)
    at /inference-server/server/node_modules/express/lib/router/index.js:281:22
    at param (/inference-server/server/node_modules/express/lib/router/index.js:354:14)
    at param (/inference-server/server/node_modules/express/lib/router/index.js:365:14)
    at param (/inference-server/server/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/inference-server/server/node_modules/express/lib/router/index.js:410:3)
```
While using the curl command the response return is correct.
```
base64 "sample.jpg" | curl -d @- \
"http://xx.xx.xx.xxx:xxxx/sample-pro/1?api_key=xxxx"
```
**Response : 200**

**Comment by yeldarby** [comment]
Sorry, it's not well documented but the inference server currently only accepts `base64` images, not multipart forms.

Try using our pip package to do inference if your application is written in python as it will handle all of this for you:

`pip install roboflow`

then

```python
from roboflow import Roboflow

rf = Roboflow(api_key="YOUR_API_KEY_HERE")
version = rf.workspace("your-workspace").project("YOUR_PROJECT").version(1, local="http://localhost:9001")

prediction = version.model.predict("YOUR_IMAGE.jpg")
print(prediction.json())
```
```
